### ISSUE TITLE
Type declaration readability

### ISSUE THREAD

**Issue by hengestone** [jtorre39/jen#21]
I don't know if you're interested in feedback for your project yet, but here goes :)

Type declarations currently have no punctuation, and it becomes hard for humans to parse when it involves  e.g. lists:
`type listStringOrNumber list stringOrNumber`
How about:
`type listStringOrNumber: list stringOrNumber`

The colon acts as a verb `is` and is consistent with the assignment and function definition syntax.

You actually used this form somewhere else in the readme ;-)
`TypeDec            = "type" varId ":" SumType`

Have fun!

**Comment by CatLoverKid** [comment]
@hengestone, feedback is definitely appreciated! This is a student project for a compiler's class. So perfection isn't guaranteed! But we still love hearing what professionals have to say about our project. We're discussing implementing this into our grammar now, it's a really nice idea actually!

**Comment by jtorre39** [comment]
Agreed, we've been meaning to improve upon the readability of type declarations actually. When we get some progress on it we'll be sure to keep this issue updated. Thanks so much for your feedback!

**Comment by hengestone** [comment]
It looks really good btw, I think having a language with type inference / minimal type annotations can be very productive, in the vein of CoffeeScript with types.

In general it helps to think of code as sentences, where punctuation can act as verbs and prepositions, as well as visual cues.

E.g. `list stringOrNumber` might be more readable as `list(stringOrNumber)` or `list[stringOrNumber]`, and similarly with `for`, `while` and even `return` to make it consistent and natural.

Code in Haskell or Purescript that looks like `iterate f 0 x 1 3 4 5 = x` instead of `iterate f(0, x, 1, 3, 4, 5) = x` just makes it unnecessarily  hard.

Good luck with your project!

**Comment by jtorre39** [comment]
Made some updates to the readme, as this issue has brought some errata to my attention. Moving forward, we'll bring your feedback up during discussion as we continue to iterate and develop!

**Comment by rtoal** [comment]
Nice to see kind folks giving advice here! Much appreciated, @hengestone.

As you guys all know Elm, check out how Evan distinguished the _definition_ of sum types from the type alias _declaration_.

Agree with @hengestone that punctuation will be nice. I know you are using Go as an insipiration, so I see where you got your style from (and that's okay! This is about learning and encountering problems during your implementation --- either your parser will complain or your users will complain at some point :) )

You are currently using the colon for separating identifiers from their types. I will leave it to your group to decide whether you want to use a colon in your sum type declaration also. You will have to consider whether that is a consistent "binding notation" or whether that overloads the colon with different meanings, since binding type names can be considered different than binding a type id to its type. Many other languages use "=" for this purpose. See what you guys come up with!

**Comment by jtorre39** [comment]
We came to the decision that the colon was a good choice to better type declaration readability. We feel as of now that the colon can be overloaded while still be sufficient in terms of sensibility. This change was already implemented in the grammar and is reflected across the language.
